name: Publish npm package

on:
  workflow_run:
    workflows: ["Build and test"]
    branches:
      - 'main'
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check for beta tag and enter beta mode if needed
        run: |
          if [[ "${{ github.event.workflow_run.head_commit.message }}" == *"[beta]"* ]]; then
            echo "Beta tag detected in commit message, entering beta mode..."
            pnpm changeset pre enter beta || echo "Already in beta mode or failed to enter"
          fi

      - name: Build
        run: pnpm build

      - name: Configure npm auth
        run: npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Version and publish packages
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version
          publish: pnpm changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
